import Foundation

/// The bridge between an agent process and the inbox.
///
/// Design rules, in order of importance:
/// 1. It can never break the agent. Every failure path exits 0 and prints nothing.
/// 2. No dependencies — plain `/bin/sh`, no jq, no python, no network.
/// 3. It reports; it never gates. Nothing here can stop an agent from working.
public enum HookScript {
    public static let version = 4

    public static let source: String = #"""
    #!/bin/sh
    # GentleMerge hook bridge (generated by `gentlemerge install` — do not edit).
    #
    # Two jobs:
    #   --mode notify    report what this session just did
    #   --mode context   report, then hand the session what the others are doing
    #
    # It must never break the agent: every failure path exits 0 silently.

    set -u
    # The payload it carries is the agent's own tool input, verbatim — it may
    # hold secrets the Redactor will only see later. Everything this script
    # writes (payload, envelope) is owner-only from birth.
    umask 077

    PROVIDER="unknown"
    MODE="notify"

    while [ $# -gt 0 ]; do
      case "$1" in
        --provider) PROVIDER="${2:-unknown}"; shift 2 ;;
        --mode) MODE="${2:-notify}"; shift 2 ;;
        *) shift ;;
      esac
    done
    # The three modes: --mode notify reports, --mode context also injects the
    # briefing, --mode advise answers a PreToolUse on the editing tools.

    INBOX_HOME="${GENTLEMERGE_HOME:-$HOME/.gentlemerge}"
    # Match Paths: Linux XDG state only when absolute and no explicit override.
    if [ -z "${GENTLEMERGE_HOME:-}" ] && [ "$(uname -s)" = "Linux" ]; then
      case "${XDG_STATE_HOME:-}" in
        /*) INBOX_HOME="$XDG_STATE_HOME/gentlemerge" ;;
      esac
    fi
    SPOOL="$INBOX_HOME/spool"
    mkdir -p "$SPOOL" 2>/dev/null || exit 0

    # --- identity -------------------------------------------------------------
    ID=$(uuidgen 2>/dev/null) || ID=""
    [ -n "$ID" ] || ID="$(date -u +%s)-$$-${RANDOM:-0}"
    NOW=$(date -u +%s)
    STAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)
    PROJECT="${CLAUDE_PROJECT_DIR:-$PWD}"

    # Inherited identity wins, as it does in Identity.resolve.
    if [ -z "${GENTLEMERGE_LABEL:-}" ]; then
      LABEL="$(git -C "$PROJECT" config --get gentlemerge.label 2>/dev/null || :)"
      [ -z "$LABEL" ] || export GENTLEMERGE_LABEL="$LABEL"
    fi

    # --- terminal -------------------------------------------------------------
    # A hook inherits the agent's controlling terminal, which is how the app
    # finds the exact window to jump to later.
    TTY_NAME=$(ps -o tty= -p $$ 2>/dev/null | tr -d ' ')
    case "$TTY_NAME" in
      ""|"?"|"??") TTY_PATH="" ;;
      /dev/*) TTY_PATH="$TTY_NAME" ;;
      *) TTY_PATH="/dev/$TTY_NAME" ;;
    esac
    # The reporter's pid. A wrapper that knows the real agent's process can
    # hand it over in GENTLEMERGE_PID — a test harness has to, because its own
    # parent is a transient shell the app would rightly bury as dead.
    AGENT_PID="${GENTLEMERGE_PID:-$(ps -o ppid= -p $$ 2>/dev/null | tr -d ' ')}"

    # --- payload --------------------------------------------------------------
    PAYLOAD_FILE="$SPOOL/.payload-$ID"
    cat > "$PAYLOAD_FILE" 2>/dev/null || :
    if [ ! -s "$PAYLOAD_FILE" ]; then
      printf '{}' > "$PAYLOAD_FILE"
    else
      FIRST=$(head -c 1 "$PAYLOAD_FILE" 2>/dev/null)
      [ "$FIRST" = "{" ] || printf '{}' > "$PAYLOAD_FILE"
    fi

    esc() {
      printf '%s' "${1:-}" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' | tr -d '\000-\037'
    }

    # Claude Code ≥ 2.1.224 exports the session's own inbox socket to its hooks.
    # A notice delivered there arrives even while the session is idle, and never
    # types into a foreign tty. Absent anywhere else — and then the app falls
    # back to the terminal it already knew, or nowhere on Linux.
    # After esc(): the shell reads top to bottom, and calling it earlier is a
    # "command not found" that mangles the envelope it was meant to extend.
    if [ -n "${CLAUDE_CODE_MESSAGING_SOCKET:-}" ]; then
      SOCKET_JSON=",\"socket\":\"$(esc "$CLAUDE_CODE_MESSAGING_SOCKET")\""
    else
      SOCKET_JSON=""
    fi

    # --- envelope -------------------------------------------------------------
    TMP="$SPOOL/.tmp-$ID"
    {
      printf '{"schema":1'
      printf ',"id":"%s"' "$(esc "$ID")"
      printf ',"provider":"%s"' "$(esc "$PROVIDER")"
      printf ',"mode":"notify"'
      printf ',"received_at":"%s"' "$STAMP"
      printf ',"cwd":"%s"' "$(esc "$PROJECT")"
      printf ',"tty":"%s"' "$(esc "$TTY_PATH")"
      printf ',"pid":"%s"' "$(esc "$AGENT_PID")"
      printf ',"term_program":"%s"' "$(esc "${TERM_PROGRAM:-}")"
      printf ',"term_session_id":"%s"' "$(esc "${TERM_SESSION_ID:-}")"
      printf '%s' "$SOCKET_JSON"
      printf ',"payload":'
      cat "$PAYLOAD_FILE"
      printf '}'
    } > "$TMP" 2>/dev/null

    # Rename is atomic: the app never reads half an envelope.
    mv "$TMP" "$SPOOL/$NOW-$ID.json" 2>/dev/null || rm -f "$TMP" 2>/dev/null

    # --- hand this session what the others are doing --------------------------
    if [ "$MODE" = "advise" ]; then
      # PreToolUse on the editing tools: warn *before* the edit lands if someone
      # else holds the path. The payload is Claude Code's own, so the CLI reads
      # tool_input.file_path out of it. Never blocks: any failure exits 0 with
      # no output, same as every other path in this script.
      CLI="$INBOX_HOME/bin/gentlemerge"
      if [ -x "$CLI" ]; then
        GENTLEMERGE_PID="$AGENT_PID" \
        "$CLI" advise --payload "$PAYLOAD_FILE" --project "$PROJECT" \
          --provider "$PROVIDER" 2>/dev/null || :
      fi
    elif [ "$MODE" = "context" ]; then
      CLI="$INBOX_HOME/bin/gentlemerge"
      if [ -x "$CLI" ]; then
        # Prints a hookSpecificOutput block, or nothing at all when there is
        # nothing new worth spending the session's context window on.
        # Without --provider the CLI has no idea who it is talking to, and
        # will not hand this session anybody else's messages.
        #
        # GENTLEMERGE_PID is the agent's own pid, which only a hook can know:
        # we are spawned by the agent, so our parent is it. The CLI run from a
        # tool call has a shell for a parent and cannot tell. Handing it over
        # here is what lets `who` bury a session the moment it dies, instead of
        # waiting out the half hour a mark is believed for.
        GENTLEMERGE_PID="$AGENT_PID" \
        "$CLI" session-context --payload "$PAYLOAD_FILE" --project "$PROJECT" \
          --provider "$PROVIDER" 2>/dev/null || :
      fi
    fi

    rm -f "$PAYLOAD_FILE" 2>/dev/null
    exit 0
    """#
}
