import GentleMergeCore
import Foundation

/// One worktree's network identity: a label, a base port, and the hundred
/// ports above it.
///
/// Dev servers collide the moment two agents run them: same framework, same
/// default port, two worktrees. So every label gets its own range, derived
/// the same way on every machine — no registry, no daemon, nothing to agree
/// on. `gentlemerge env` prints it; `env --write` saves it as
/// `.gentlemerge/env.sh` for the shell to source.
public enum WorktreeEnv {
    /// Ports per label. The step between two labels' bases, so index-derived
    /// ranges never overlap.
    public static let rangeSize = 100
    /// The highest port the 16-bit space allows.
    public static let highestPort = 65_535

    /// Buckets for labels the config never heard of.
    ///
    /// Fifty buckets of a hundred ports look generous and are not: a pair of
    /// labels collides with probability 1/50, and realistic ones land on each
    /// other — `gemini` and `gpt` both hashed to 3800, `opencode` and `qwen` to
    /// 6800, so two agents ran one dev-server port range exactly as the README
    /// promises they would not (audit 2026-10-08). 256 buckets makes that
    /// ~1/256, and `usableBuckets` keeps the arithmetic inside the port range
    /// whatever `basePort` is, degrading toward the old density rather than
    /// emitting an invalid port.
    public static let fallbackBuckets = 256

    /// How many buckets fit above `basePort` without leaving the port range.
    static func usableBuckets(basePort: Int) -> Int {
        max(1, min(fallbackBuckets, (highestPort - basePort + 1) / rangeSize))
    }

    public struct Allocation: Sendable, Equatable {
        public var label: String
        public var base: Int
        public var range: ClosedRange<Int>

        public init(label: String, base: Int) {
            self.label = label
            self.base = base
            self.range = base...(base + WorktreeEnv.rangeSize - 1)
        }
    }

    /// FNV-1a over the label's bytes. Swift's own Hasher is deliberately
    /// unstable across runs, which is exactly wrong here: the same label must
    /// get the same ports every time, on every machine.
    public static func stableHash(_ label: String) -> UInt32 {
        var hash: UInt32 = 2_166_136_261
        for byte in label.utf8 {
            hash ^= UInt32(byte)
            hash = hash &* 16_777_619
        }
        return hash
    }

    /// A fixed `portBase` on the agent wins; otherwise the label's position in
    /// `config.agents`, a hundred ports apart; otherwise a stable hash bucket
    /// for a label nobody configured.
    public static func allocation(label: String, config: AppConfig) -> Allocation {
        if let agent = config.agents.first(where: { $0.label == label }),
           let portBase = agent.portBase {
            return Allocation(label: label, base: portBase)
        }
        if let index = config.agents.firstIndex(where: { $0.label == label }) {
            return Allocation(label: label, base: config.basePort + rangeSize * index)
        }
        let bucket = Int(stableHash(label) % UInt32(usableBuckets(basePort: config.basePort)))
        return Allocation(label: label, base: config.basePort + rangeSize * bucket)
    }

    /// Single-quote a value for a POSIX shell — the shared primitive, kept as a
    /// name so the generated file reads the way it always has.
    ///
    /// This file exists to be `source`d, so every value in it is shell code, not
    /// a string. The label used to be interpolated bare, and it reaches here
    /// from `WorktreeLabel.read` — which only trims whitespace — or from
    /// `GENTLEMERGE_NAME` raw; `Identity.safe` is applied to env and presence
    /// labels but never to the worktree label. A label of `$(id)` therefore
    /// wrote `export GENTLEMERGE_LABEL=$(id)` and ran `id` on the next `source`
    /// (audit 2026-10-07).
    static func shellQuoted(_ value: String) -> String { Shell.quoted(value) }

    public static func render(_ allocation: Allocation) -> String {
        let label = shellQuoted(allocation.label)
        let suffix = shellQuoted("_" + allocation.label)
        return """
        # generated by gentlemerge — source me before running dev servers
        export GENTLEMERGE_LABEL=\(label)
        export PORT=\(allocation.base) AGENT_PORT_BASE=\(allocation.base) AGENT_PORT_RANGE=\(allocation.range.lowerBound)-\(allocation.range.upperBound)
        export DATABASE_URL_SUFFIX=\(suffix)
        """
    }

    /// `project init` keeps `.gentlemerge/env.sh` out of git: generated ports
    /// are local truth, and committing them would hand every clone the same
    /// range — the collision this exists to avoid. Idempotent.
    public static func ensureGitignore(projectPath: String) {
        let url = URL(fileURLWithPath: projectPath).appendingPathComponent(".gitignore")
        let line = ".gentlemerge/env.sh"
        let existing = (try? String(contentsOf: url, encoding: .utf8)) ?? ""
        let present = existing
            .components(separatedBy: "\n")
            .map { $0.trimmingCharacters(in: .whitespaces) }
            .contains(line)
        guard !present else { return }
        let separator = existing.isEmpty ? "" : (existing.hasSuffix("\n") ? "" : "\n")
        try? AtomicFile.write(Data((existing + separator + line + "\n").utf8), to: url)
    }
}
