import GentleMergeCore
import Foundation

/// One worktree's network identity: a label, a base port, and the hundred
/// ports above it.
///
/// Dev servers collide the moment two agents run them: same framework, same
/// default port, two worktrees. So every label gets its own range, derived
/// the same way on every machine — no registry, no daemon, nothing to agree
/// on. `gentlemerge env` prints it; `env --write` saves it as
/// `.gentlemerge/env.sh` for the shell to source.
public enum WorktreeEnv {
    /// Ports per label. The step between two labels' bases, so index-derived
    /// ranges never overlap.
    public static let rangeSize = 100
    /// Buckets for labels the config never heard of. Fifty buckets of a
    /// hundred ports: collisions are possible in theory, and in practice the
    /// fix is one line in config.json.
    public static let fallbackBuckets = 50

    public struct Allocation: Sendable, Equatable {
        public var label: String
        public var base: Int
        public var range: ClosedRange<Int>

        public init(label: String, base: Int) {
            self.label = label
            self.base = base
            self.range = base...(base + WorktreeEnv.rangeSize - 1)
        }
    }

    /// FNV-1a over the label's bytes. Swift's own Hasher is deliberately
    /// unstable across runs, which is exactly wrong here: the same label must
    /// get the same ports every time, on every machine.
    public static func stableHash(_ label: String) -> UInt32 {
        var hash: UInt32 = 2_166_136_261
        for byte in label.utf8 {
            hash ^= UInt32(byte)
            hash = hash &* 16_777_619
        }
        return hash
    }

    /// A fixed `portBase` on the agent wins; otherwise the label's position in
    /// `config.agents`, a hundred ports apart; otherwise a stable hash bucket
    /// for a label nobody configured.
    public static func allocation(label: String, config: AppConfig) -> Allocation {
        if let agent = config.agents.first(where: { $0.label == label }),
           let portBase = agent.portBase {
            return Allocation(label: label, base: portBase)
        }
        if let index = config.agents.firstIndex(where: { $0.label == label }) {
            return Allocation(label: label, base: config.basePort + rangeSize * index)
        }
        let bucket = Int(stableHash(label) % UInt32(fallbackBuckets))
        return Allocation(label: label, base: config.basePort + rangeSize * bucket)
    }

    public static func render(_ allocation: Allocation) -> String {
        """
        # generated by gentlemerge — source me before running dev servers
        export GENTLEMERGE_LABEL=\(allocation.label)
        export PORT=\(allocation.base) AGENT_PORT_BASE=\(allocation.base) AGENT_PORT_RANGE=\(allocation.range.lowerBound)-\(allocation.range.upperBound)
        export DATABASE_URL_SUFFIX=_\(allocation.label)
        """
    }

    /// `project init` keeps `.gentlemerge/env.sh` out of git: generated ports
    /// are local truth, and committing them would hand every clone the same
    /// range — the collision this exists to avoid. Idempotent.
    public static func ensureGitignore(projectPath: String) {
        let url = URL(fileURLWithPath: projectPath).appendingPathComponent(".gitignore")
        let line = ".gentlemerge/env.sh"
        let existing = (try? String(contentsOf: url, encoding: .utf8)) ?? ""
        let present = existing
            .components(separatedBy: "\n")
            .map { $0.trimmingCharacters(in: .whitespaces) }
            .contains(line)
        guard !present else { return }
        let separator = existing.isEmpty ? "" : (existing.hasSuffix("\n") ? "" : "\n")
        try? AtomicFile.write(Data((existing + separator + line + "\n").utf8), to: url)
    }
}
