import Foundation

/// A cheap sketch of how a project is put together: what it is written in, how
/// it is built and tested, where the code sits, and which files to open first.
///
/// Every new session of every model otherwise spends its first minutes
/// rediscovering the same shape, and pays for it out of its context window. So
/// this is generated rather than written by hand, and sealed with the commit it
/// was built from — a reader can tell with one command whether it still
/// describes the repository in front of them.
public struct ProjectMap: Codable, Sendable, Equatable {
    /// Languages and toolchain, most used first.
    public var stack: [String]
    /// The commands this project actually verifies itself with.
    public var commands: [String]
    /// Code files found, ignoring dependencies and build output.
    public var fileCount: Int
    /// "Sources (32)" — the first-level directories that hold the code.
    public var directories: [String]
    /// A handful of files worth opening first: entry points, then the largest.
    public var hubs: [String]
    /// HEAD when this was built, or nil outside a git repository.
    public var commit: String?
    public var builtAt: Date

    public init(
        stack: [String] = [],
        commands: [String] = [],
        fileCount: Int = 0,
        directories: [String] = [],
        hubs: [String] = [],
        commit: String? = nil,
        builtAt: Date = Date()
    ) {
        self.stack = stack
        self.commands = commands
        self.fileCount = fileCount
        self.directories = directories
        self.hubs = hubs
        self.commit = commit
        self.builtAt = builtAt
    }

    /// Nothing was found worth telling anyone about — an empty directory, or a
    /// folder that is not a project at all.
    public var isEmpty: Bool {
        stack.isEmpty && commands.isEmpty && hubs.isEmpty && fileCount == 0
    }

    public var shortCommit: String? { Self.abbreviated(commit) }

    /// The file only ever carries the short form — it is what a reader compares
    /// by eye — so every comparison is made on the short form too, whichever
    /// end the full revision came in on.
    static func abbreviated(_ sha: String?) -> String? {
        guard let sha, !sha.isEmpty else { return nil }
        return String(sha.prefix(8))
    }

    /// Whether this map still describes the revision it claims to.
    public func isSealed(with head: String?) -> Bool {
        Self.abbreviated(commit) == Self.abbreviated(head)
    }

    /// Only ever true when we know both ends: a project with no git has no
    /// commit to drift from, so it is never stale.
    public func isStale(comparedTo head: String?) -> Bool {
        guard let mine = Self.abbreviated(commit), let theirs = Self.abbreviated(head) else { return false }
        return mine != theirs
    }

    // MARK: - What a session is told

    /// The map as it goes into a session's context. Kept to a handful of lines:
    /// it is charged to every session that starts, in every project.
    public func briefingLines(head: String? = nil) -> [String] {
        guard !isEmpty else { return [] }
        var lines = ["Project map (generated by GentleMerge from the files on disk):"]

        if !stack.isEmpty { lines.append("- Stack: \(stack.joined(separator: " · "))") }
        if !commands.isEmpty { lines.append("- Build & test: \(commands.joined(separator: " · "))") }
        if fileCount > 0 { lines.append("- Shape: \(shapeSentence)") }
        if !hubs.isEmpty { lines.append("- Start here: \(hubs.joined(separator: " · "))") }

        if let short = shortCommit {
            if isStale(comparedTo: head), let now = head {
                lines.append(
                    "- Built at commit \(short); HEAD is now \(String(now.prefix(8))) — may be stale,"
                        + " check the files before trusting it."
                )
            } else {
                lines.append(
                    "- Built from commit \(short) on \(HandoffMarkdown.dayFormatter.string(from: builtAt))"
                        + " — `git rev-parse HEAD` to check it is still current."
                )
            }
        } else {
            lines.append(
                "- Built on \(HandoffMarkdown.dayFormatter.string(from: builtAt)); no git here, so nothing pins it."
            )
        }

        return lines
    }

    public var shapeSentence: String {
        let files = "\(fileCount) code \(fileCount == 1 ? "file" : "files")"
        guard !directories.isEmpty else { return files }
        return "\(files) — \(directories.joined(separator: ", "))"
    }

    // MARK: - Building one

    /// Directories that are somebody else's code, or output we produced. Matched
    /// by name *before* descending: a 500 MB node_modules must never be walked,
    /// not even to throw the results away.
    static let ignoredDirectories: Set<String> = [
        "node_modules", "bower_components", "vendor", "Pods", "Carthage", "DerivedData",
        "build", "dist", "out", "target", "bin", "obj", "coverage", "__pycache__",
        "venv", "env", "virtualenv", "site-packages", "worktrees", "tmp", "temp",
        "Library", "Frameworks", "third_party", "Generated", "snapshots",
    ]

    /// Extensions that mean "somebody wrote this". Markdown, JSON and assets are
    /// deliberately out: they inflate the count without describing the project.
    static let codeExtensions: Set<String> = [
        "swift", "m", "mm", "h", "c", "cc", "cpp", "hpp", "kt", "kts", "java", "scala",
        "ts", "tsx", "js", "jsx", "mjs", "cjs", "vue", "svelte",
        "py", "rb", "go", "rs", "php", "cs", "dart", "ex", "exs", "lua", "sh", "sql", "r",
    ]

    /// Files that are where you start reading, by convention.
    static let entryPointNames: Set<String> = [
        "main.swift", "App.swift", "main.go", "main.rs", "main.py", "__main__.py",
        "index.js", "index.ts", "index.tsx", "main.ts", "main.tsx",
        "App.js", "App.jsx", "App.tsx", "server.js", "server.ts",
    ]

    /// Root files that answer "what is this and how do I run it".
    static let manifestNames = ["Package.swift", "package.json", "Cargo.toml", "go.mod", "pyproject.toml"]

    /// A ceiling on the walk, so a pathological tree costs a bounded amount of
    /// time at the start of a session rather than an unbounded one.
    static let entryBudget = 20_000
    static let maximumDepth = 8
    static let maximumHubs = 6
    /// A file this big is a bundle or a generated table. It may well be the
    /// largest thing in the repository; it is never where you start reading.
    static let largestReadableHub = 200_000

    public static func build(for projectPath: String, head: String?, now: Date = Date()) -> ProjectMap {
        let root = URL(fileURLWithPath: projectPath)
        let scan = walk(root)

        return ProjectMap(
            stack: stack(for: root, scan: scan),
            commands: commands(for: root),
            fileCount: scan.total,
            directories: topDirectories(scan),
            hubs: hubs(for: root, scan: scan),
            commit: abbreviated(head),
            builtAt: now
        )
    }

    // MARK: - Walking the tree

    struct Scan {
        var total = 0
        var byExtension: [String: Int] = [:]
        var byTopLevel: [String: Int] = [:]
        var largest: [(path: String, size: Int)] = []
        var entryPoints: [(path: String, depth: Int)] = []
    }

    static func walk(_ root: URL) -> Scan {
        var scan = Scan()
        let manager = FileManager.default
        let rootPath = root.standardizedFileURL.path
        var queue: [(url: URL, depth: Int, top: String?)] = [(root, 0, nil)]
        var visited = 0

        while !queue.isEmpty, visited < entryBudget {
            let (directory, depth, top) = queue.removeFirst()
            guard
                let entries = try? manager.contentsOfDirectory(
                    at: directory,
                    includingPropertiesForKeys: [.isDirectoryKey, .fileSizeKey],
                    // Hidden entries take .git, .build and .venv out of the walk
                    // for free, and hold nothing a newcomer needs to read.
                    options: [.skipsHiddenFiles, .skipsPackageDescendants]
                )
            else { continue }

            for entry in entries {
                visited += 1
                if visited >= entryBudget { break }
                let name = entry.lastPathComponent
                let values = try? entry.resourceValues(forKeys: [.isDirectoryKey, .fileSizeKey])

                if values?.isDirectory == true {
                    guard depth < maximumDepth, !ignoredDirectories.contains(name) else { continue }
                    queue.append((entry, depth + 1, top ?? name))
                    continue
                }

                let ext = entry.pathExtension.lowercased()
                guard codeExtensions.contains(ext), !isGenerated(name) else { continue }

                scan.total += 1
                scan.byExtension[ext, default: 0] += 1
                if let top { scan.byTopLevel[top, default: 0] += 1 }

                let relative = relativePath(of: entry, under: rootPath)
                if entryPointNames.contains(name) {
                    scan.entryPoints.append((relative, depth))
                }
                let size = values?.fileSize ?? 0
                if size <= largestReadableHub { scan.largest.append((relative, size)) }
            }
        }

        // Only the head of this list is ever used, but sorting a few thousand
        // pairs once is cheaper than maintaining a heap while walking.
        scan.largest.sort { $0.size > $1.size }
        scan.largest = Array(scan.largest.prefix(maximumHubs * 2))
        scan.entryPoints.sort { ($0.depth, $0.path) < ($1.depth, $1.path) }
        return scan
    }

    /// Minified and bundled output is code nobody wrote and nobody reads. It is
    /// checked in often enough to distort both the count and the hub list.
    static func isGenerated(_ name: String) -> Bool {
        let lowered = name.lowercased()
        return lowered.contains(".min.") || lowered.contains("-min.") || lowered.contains(".bundle.")
    }

    static func relativePath(of url: URL, under rootPath: String) -> String {
        let path = url.standardizedFileURL.path
        guard path.hasPrefix(rootPath + "/") else { return url.lastPathComponent }
        return String(path.dropFirst(rootPath.count + 1))
    }

    // MARK: - Reading the scan

    static func topDirectories(_ scan: Scan) -> [String] {
        scan.byTopLevel
            .filter { $0.value > 0 }
            .sorted { ($0.value, $1.key) > ($1.value, $0.key) }
            .prefix(5)
            .map { "\($0.key) (\($0.value))" }
    }

    static let languageNames: [String: String] = [
        "swift": "Swift", "m": "Objective-C", "mm": "Objective-C++", "h": "C headers",
        "c": "C", "cc": "C++", "cpp": "C++", "hpp": "C++", "kt": "Kotlin", "kts": "Kotlin",
        "java": "Java", "scala": "Scala", "ts": "TypeScript", "tsx": "TypeScript",
        "js": "JavaScript", "jsx": "JavaScript", "mjs": "JavaScript", "cjs": "JavaScript",
        "vue": "Vue", "svelte": "Svelte", "py": "Python", "rb": "Ruby", "go": "Go",
        "rs": "Rust", "php": "PHP", "cs": "C#", "dart": "Dart", "ex": "Elixir",
        "exs": "Elixir", "lua": "Lua", "sh": "Shell", "sql": "SQL", "r": "R",
    ]

    static func stack(for root: URL, scan: Scan) -> [String] {
        var byLanguage: [String: Int] = [:]
        for (ext, count) in scan.byExtension {
            guard let language = languageNames[ext] else { continue }
            byLanguage[language, default: 0] += count
        }

        let languages = byLanguage
            .sorted { ($0.value, $1.key) > ($1.value, $0.key) }
            .prefix(3)
            .map(\.key)

        return languages + toolchain(for: root)
    }

    static func toolchain(for root: URL) -> [String] {
        let manager = FileManager.default
        func exists(_ name: String) -> Bool {
            manager.fileExists(atPath: root.appendingPathComponent(name).path)
        }

        var found: [String] = []
        if exists("Package.swift") { found.append("SwiftPM") }
        if exists("package.json") { found.append(ProjectChecks.packageRunner(in: root)) }
        if exists("Cargo.toml") { found.append("Cargo") }
        if exists("go.mod") { found.append("Go modules") }
        if exists("pyproject.toml") || exists("setup.py") { found.append("Python packaging") }
        if ProjectChecks.xcodeScheme(in: root) != nil { found.append("Xcode") }
        if exists("Dockerfile") { found.append("Docker") }
        return found
    }

    static func commands(for root: URL) -> [String] {
        // The same detection `gentlemerge review` runs, so the map can never
        // advertise a command the rest of the app would not use.
        let wanted: [Check.Kind] = [.build, .test, .typecheck]
        var seen = Set<String>()
        return ProjectChecks.checks(for: root)
            .filter { !$0.optional && wanted.contains($0.kind) }
            .map(\.command)
            .filter { seen.insert($0).inserted }
            .prefix(3)
            .map { "`\($0)`" }
    }

    static func hubs(for root: URL, scan: Scan) -> [String] {
        var picked: [String] = []
        func add(_ path: String) {
            guard picked.count < maximumHubs, !picked.contains(path) else { return }
            picked.append(path)
        }

        let manager = FileManager.default
        for manifest in manifestNames
        where manager.fileExists(atPath: root.appendingPathComponent(manifest).path) {
            add(manifest)
            if picked.count == 2 { break }
        }

        for entry in scan.entryPoints.prefix(3) { add(entry.path) }
        for file in scan.largest { add(file.path) }
        return picked
    }
}
