import XCTest
@testable import GentleMergeCore
@testable import GentleMergePorts

/// One worktree, one port range: fixed bases win, then position, then a
/// stable hash — and the same label always lands in the same place.
final class WorktreeEnvTests: XCTestCase {
    private func config(agents: [AgentTarget] = [], basePort: Int = 3000) -> AppConfig {
        var config = AppConfig()
        config.agents = agents
        config.basePort = basePort
        return config
    }

    func testAFixedPortBaseWins() {
        let config = config(agents: [AgentTarget(label: "claude", portBase: 3100)])
        let found = WorktreeEnv.allocation(label: "claude", config: config)
        XCTAssertEqual(found.base, 3100)
        XCTAssertEqual(found.range, 3100...3199)
    }

    /// Two labels in the list sit a hundred ports apart, so their ranges
    /// cannot overlap.
    func testTwoLabelsGetDisjointRanges() {
        let config = config(agents: [AgentTarget(label: "a"), AgentTarget(label: "b")])
        let a = WorktreeEnv.allocation(label: "a", config: config)
        let b = WorktreeEnv.allocation(label: "b", config: config)
        XCTAssertEqual(a.base, 3000)
        XCTAssertEqual(b.base, 3100)
        XCTAssertTrue(a.range.upperBound < b.range.lowerBound)
    }

    func testAnUnknownLabelFallsBackToAStableHashBucket() {
        let config = config()
        let first = WorktreeEnv.allocation(label: "hermes", config: config)
        let second = WorktreeEnv.allocation(label: "hermes", config: config)
        XCTAssertEqual(first, second)
        XCTAssertEqual(first.base % 100, 0)
        XCTAssertTrue((3000...7900).contains(first.base))
    }

    func testRenderMatchesTheDocumentedShape() {
        XCTAssertEqual(
            WorktreeEnv.render(WorktreeEnv.Allocation(label: "claude", base: 3100)),
            """
            # generated by gentlemerge — source me before running dev servers
            export GENTLEMERGE_LABEL=claude
            export PORT=3100 AGENT_PORT_BASE=3100 AGENT_PORT_RANGE=3100-3199
            export DATABASE_URL_SUFFIX=_claude
            """
        )
    }

    func testOldConfigsDecodeWithADefaultBasePort() throws {
        let decoded = try JSONCoding.decoder().decode(AppConfig.self, from: Data("{}".utf8))
        XCTAssertEqual(decoded.basePort, 3000)
        XCTAssertTrue(decoded.agents.isEmpty)
    }

    func testEnsureGitignoreIsIdempotentAndKeepsWhatWasThere() throws {
        let directory = URL(fileURLWithPath: NSTemporaryDirectory())
            .appendingPathComponent("gentlemerge-env-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: directory) }
        let ignore = directory.appendingPathComponent(".gitignore")

        WorktreeEnv.ensureGitignore(projectPath: directory.path)
        WorktreeEnv.ensureGitignore(projectPath: directory.path)
        XCTAssertEqual(try String(contentsOf: ignore, encoding: .utf8), ".gentlemerge/env.sh\n")

        try Data("node_modules/\n".utf8).write(to: ignore)
        WorktreeEnv.ensureGitignore(projectPath: directory.path)
        XCTAssertEqual(
            try String(contentsOf: ignore, encoding: .utf8),
            "node_modules/\n.gentlemerge/env.sh\n"
        )
    }
}
