import XCTest
@testable import GentleMergeCore
@testable import GentleMergePorts

/// One worktree, one port range: fixed bases win, then position, then a
/// stable hash — and the same label always lands in the same place.
final class WorktreeEnvTests: XCTestCase {
    private func config(agents: [AgentTarget] = [], basePort: Int = 3000) -> AppConfig {
        var config = AppConfig()
        config.agents = agents
        config.basePort = basePort
        return config
    }

    func testAFixedPortBaseWins() {
        let config = config(agents: [AgentTarget(label: "claude", portBase: 3100)])
        let found = WorktreeEnv.allocation(label: "claude", config: config)
        XCTAssertEqual(found.base, 3100)
        XCTAssertEqual(found.range, 3100...3199)
    }

    /// Two labels in the list sit a hundred ports apart, so their ranges
    /// cannot overlap.
    func testTwoLabelsGetDisjointRanges() {
        let config = config(agents: [AgentTarget(label: "a"), AgentTarget(label: "b")])
        let a = WorktreeEnv.allocation(label: "a", config: config)
        let b = WorktreeEnv.allocation(label: "b", config: config)
        XCTAssertEqual(a.base, 3000)
        XCTAssertEqual(b.base, 3100)
        XCTAssertTrue(a.range.upperBound < b.range.lowerBound)
    }

    func testAnUnknownLabelFallsBackToAStableHashBucket() {
        let config = config()
        let first = WorktreeEnv.allocation(label: "hermes", config: config)
        let second = WorktreeEnv.allocation(label: "hermes", config: config)
        XCTAssertEqual(first, second)
        XCTAssertEqual(first.base % 100, 0)
        XCTAssertTrue((3000...WorktreeEnv.highestPort).contains(first.base))
    }

    /// The fallback space used to be 50 buckets of a hundred ports, which
    /// collides for realistic labels: `gemini` and `gpt` shared a base, and so
    /// did `opencode` and `qwen` — two agents on one dev-server port range, the
    /// exact thing this module exists to prevent (audit 2026-10-08).
    func testRealisticUnconfiguredLabelsDoNotShareAPortRange() {
        let config = config()
        var bases: [String: Int] = [:]
        for label in ["claude", "codex", "hermes", "gemini", "opencode", "qwen",
                      "gpt", "aider", "cursor", "cline", "continue", "amp", "droid"] {
            let base = WorktreeEnv.allocation(label: label, config: config).base
            if let clash = bases.first(where: { $0.value == base }) {
                XCTFail("\(label) and \(clash.key) share port base \(base)")
            }
            bases[label] = base
        }
    }

    /// A high `basePort` must not push a range past the port space: the bucket
    /// arithmetic degrades toward the old density instead of emitting an
    /// impossible port.
    func testAHighBasePortStillYieldsAValidPort() {
        let config = config(basePort: 65_000)
        for label in ["a", "b", "c", "d", "e", "f", "g", "h"] {
            let found = WorktreeEnv.allocation(label: label, config: config)
            XCTAssertTrue((65_000...WorktreeEnv.highestPort).contains(found.range.upperBound),
                          "\(label) -> \(found.range) leaves the port range")
        }
    }

    func testRenderMatchesTheDocumentedShape() {
        // Values are single-quoted. This file is `source`d, so every value in it
        // is shell code, and the label is not ours to trust — it reached here
        // from a worktree label that only whitespace-trims. `$(id)` as a label
        // used to run `id` on the next `source` (audit 2026-10-07). See
        // ShellQuotingTests, which sources the real file with a real /bin/sh.
        XCTAssertEqual(
            WorktreeEnv.render(WorktreeEnv.Allocation(label: "claude", base: 3100)),
            """
            # generated by gentlemerge — source me before running dev servers
            export GENTLEMERGE_LABEL='claude'
            export PORT=3100 AGENT_PORT_BASE=3100 AGENT_PORT_RANGE=3100-3199
            export DATABASE_URL_SUFFIX='_claude'
            """
        )
    }

    func testOldConfigsDecodeWithADefaultBasePort() throws {
        let decoded = try JSONCoding.decoder().decode(AppConfig.self, from: Data("{}".utf8))
        XCTAssertEqual(decoded.basePort, 3000)
        XCTAssertTrue(decoded.agents.isEmpty)
    }

    func testEnsureGitignoreIsIdempotentAndKeepsWhatWasThere() throws {
        let directory = URL(fileURLWithPath: NSTemporaryDirectory())
            .appendingPathComponent("gentlemerge-env-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: directory) }
        let ignore = directory.appendingPathComponent(".gitignore")

        WorktreeEnv.ensureGitignore(projectPath: directory.path)
        WorktreeEnv.ensureGitignore(projectPath: directory.path)
        XCTAssertEqual(try String(contentsOf: ignore, encoding: .utf8), ".gentlemerge/env.sh\n")

        try Data("node_modules/\n".utf8).write(to: ignore)
        WorktreeEnv.ensureGitignore(projectPath: directory.path)
        XCTAssertEqual(
            try String(contentsOf: ignore, encoding: .utf8),
            "node_modules/\n.gentlemerge/env.sh\n"
        )
    }
}
